modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/BOs-Fire-Extinguisher/issues"

[[mods]]
modId = "fire_extinguisher"
version = "${file.jarVersion}"
displayName = "Fire Extinguisher"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/fire-extinguisher"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''Enhance your fire safety with a straightforward and effective fire extinguisher modification that incorporates essential items for combating fires.'''

[[dependencies.fire_extinguisher]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fire_extinguisher]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
