# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Project
version=8.3.0
group=de.markusbordihn.fireextinguisher
vendor_name=markusbordihn
# Mod
mod_id=fire_extinguisher
mod_name=Fire Extinguisher
mod_author=Markus Bordihn
mod_namespace=fireextinguisher
# Common
minecraft_version=1.21.10
neo_form_version=1.21.10-20251010.172816
# Forge Mod Loader
forge_version=60.1.0
# Forge Helper Mods
forge_jei_mod=
forge_xaeros_minimap_mod=
# Fabric Mod Loader
fabric_version=0.138.3+1.21.10
fabric_loader_version=0.18.1
fabric_loom=1.13-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=7182173
fabric_xaeros_minimap_mod=
# NeoForge Mod Loader
neoforge_version=21.10.63
# NeoForge Helper Mods
neoforge_jei_mod=7182174
neoforge_xaeros_minimap_mod=
# Publish to CurseForge
curseforge_release_type=beta
curseforge_project_id=567225
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=beta
modrinth_project_id=GlhPy70K
modrinth_api_token=Never put your token here!
