# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Project
version=8.3.1
group=de.markusbordihn.fireextinguisher
vendor_name=markusbordihn
# Mod
mod_id=fire_extinguisher
mod_name=Fire Extinguisher
mod_author=Markus Bordihn
mod_namespace=fireextinguisher
# Common
minecraft_version=1.21.3
# Forge Mod Loader
forge_version=53.0.33
# Forge Helper Mods
forge_jei_mod=
forge_spark_mod=5924845
forge_xaeros_minimap_mod=5890969
# Fabric Mod Loader
fabric_version=0.112.1+1.21.3
fabric_loader_version=0.16.9
fabric_loom=1.9-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=
fabric_spark_mod=
fabric_xaeros_minimap_mod=5890974
fabric_jade_mod=5846071
# NeoForge Mod Loader
neoforge_version=21.3.58
# NeoForge Helper Mods
neoforge_jei_mod=
neoforge_spark_mod=5924848
neoforge_xaeros_minimap_mod=5890971
neoforge_jade_mod=5846076
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=567225
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=GlhPy70K
modrinth_api_token=Never put your token here!
